-- Run this in the Supabase SQL Editor to set up the database.

-- Records table: a dated expense that groups one or more line items.
create table if not exists public.records (
  id bigint generated by default as identity primary key,
  date date not null,
  title text not null default '',
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Items table: each line item belongs to a record.
create table if not exists public.items (
  id bigint generated by default as identity primary key,
  record_id bigint not null references public.records(id) on delete cascade,
  description text not null default '',
  amount numeric(12,2) not null default 0
);

create index if not exists items_record_id_idx on public.items(record_id);

-- Row Level Security: allow all operations for the service role and anon (demo).
-- For production, restrict this to authenticated users.
alter table public.records enable row level security;
alter table public.items enable row level security;

create policy "allow all records" on public.records for all using (true) with check (true);
create policy "allow all items" on public.items for all using (true) with check (true);
