-- Run this in the Supabase SQL Editor to set up the database.

-- Records table: a dated expense that groups one or more line items.
create table if not exists public.records (
  id bigint generated by default as identity primary key,
  date date not null,
  category text not null default 'Other',
  title text not null default '',
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Add the category column to an existing records table (idempotent).
alter table public.records add column if not exists category text not null default 'Other';

-- Categories table: predefined + user-added options for the dropdown.
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

-- Seed with some default categories.
insert into public.categories (name) values
  ('Food & Drink'),
  ('Transport'),
  ('Shopping'),
  ('Housing'),
  ('Utilities'),
  ('Entertainment'),
  ('Health'),
  ('Groceries'),
  ('Other')
on conflict (name) do nothing;

-- Items table: each line item belongs to a record.
create table if not exists public.items (
  id bigint generated by default as identity primary key,
  record_id bigint not null references public.records(id) on delete cascade,
  description text not null default '',
  amount numeric(12,2) not null default 0
);

-- Remove the now-unused category column from items (idempotent).
alter table public.items drop column if exists category;

create index if not exists items_record_id_idx on public.items(record_id);

-- Row Level Security: allow all operations for the service role and anon (demo).
-- For production, restrict this to authenticated users.
alter table public.records enable row level security;
alter table public.items enable row level security;
alter table public.categories enable row level security;

create policy "allow all records" on public.records for all using (true) with check (true);
create policy "allow all items" on public.items for all using (true) with check (true);
create policy "allow all categories" on public.categories for all using (true) with check (true);

