const { Client } = require("pg");

const sql = `
-- Records table
create table if not exists public.records (
  id bigint generated by default as identity primary key,
  date date not null,
  title text not null default '',
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Items table
create table if not exists public.items (
  id bigint generated by default as identity primary key,
  record_id bigint not null references public.records(id) on delete cascade,
  description text not null default '',
  amount numeric(12,2) not null default 0
);

create index if not exists items_record_id_idx on public.items(record_id);

-- Row Level Security
alter table public.records enable row level security;
alter table public.items enable row level security;

-- Allow anon/authenticated access (permissive for this personal tracker)
do $$
begin
  if not exists (select 1 from pg_policies where tablename='records' and policyname='allow_all_records') then
    create policy "allow_all_records" on public.records for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='items' and policyname='allow_all_items') then
    create policy "allow_all_items" on public.items for all using (true) with check (true);
  end if;
end $$;
`;

async function main() {
  const conn = process.env.PG_CONNECTION_STRING;
  if (!conn) {
    console.error("PG_CONNECTION_STRING env var is required");
    process.exit(1);
  }

  const client = new Client({ connectionString: conn, ssl: { rejectUnauthorized: false } });

  try {
    await client.connect();
    console.log("Connected to PostgreSQL");
    await client.query(sql);
    console.log("Schema created successfully (records + items tables)");

    const res = await client.query(
      "select table_name from information_schema.tables where table_schema='public' and table_name in ('records','items') order by table_name"
    );
    console.log("Verified tables:", res.rows.map((r) => r.table_name).join(", "));
  } catch (err) {
    console.error("Error:", err.message);
    process.exit(1);
  } finally {
    await client.end();
  }
}

main();
